### ISSUE TITLE
Android app crashing on launch

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-installer-android#164] opened 2023-07-20 09:30 UTC
[Uploading crash.log…]()
With the latest releases, the android app fails to work as it crashes right away after launching it.
Tried the windows app, the issue cannot be duplicated.
Also, the version cannot be obtained from the app info anymore.

Reproduce steps:
1. Install the latest internal testing app from the google store
2. Open the app
3. Check the status
4. Check the app version by: Right click on the Endless Key app icon -> App info -> More settings and permissions -> Advanced

Results:

**For Step3:** 
7/19 package:
- Windows: 6.29.1.0 -> Can proceed to the the content pack selection and complete the download process
- Android: version unknown -> app crashed after launching (android 9 & 11)

7/20 package:
- Windows: 6.30.1.0 -> Can proceed to the the content pack selection and complete the download process & the app works after updated from v6.29.1.0
- Android: version unknown -> app crashed after launching (tested on an android 11)

**For Step4**
No version info is shown in the field.

**Comment by dbnicholson** [comment] 2023-07-20 16:29
The version issue should hopefully be fixed by #165. Here's the backtrace @wjt posted on slack:

```
2023-07-20 16:42:49.729  1922-1995  python                  <pre-initialized>                    I  Traceback (most recent call last):
2023-07-20 16:42:49.729  1922-1995  python                  <pre-initialized>                    I    File "/home/jenkins/workspace/kolibri-installer-android/src/main.py", line 1, in <module>
2023-07-20 16:42:49.731  1922-1995  python                  <pre-initialized>                    I    File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri_android/main_activity/__main__.py", line 1, in <module>
2023-07-20 16:42:49.731  1922-1995  python                  <pre-initialized>                    I    File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri_android/globals.py", line 10, in <module>
2023-07-20 16:42:49.732  1922-1995  python                  <pre-initialized>                    I    File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri_android/android_utils.py", line 18, in <module>
2023-07-20 16:42:49.732  1922-1995  python                  <pre-initialized>                    I    File "/home/jenkins/workspace/kolibri-installer-android/_cache/.local/share/python-for-android/build/python-installs/kolibri/x86_64/android/__init__.py", line 8, in <module>
2023-07-20 16:42:49.732  1922-1995  python                  <pre-initialized>                    I    File "android/_android.pyx", line 158, in init android._android
2023-07-20 16:42:49.733  1922-1995  python                  <pre-initialized>                    I    File "/home/jenkins/workspace/kolibri-installer-android/_cache/.local/share/python-for-android/build/python-installs/kolibri/x86_64/jnius/reflect.py", line 211, in autoclass
2023-07-20 16:42:49.733  1922-1995  python                  <pre-initialized>                    I    File "jnius/jnius_export_func.pxi", line 28, in jnius.jnius.find_javaclass
2023-07-20 16:42:49.733  1922-1995  python                  <pre-initialized>                    I    File "jnius/jnius_export_class.pxi", line 267, in jnius.jnius.JavaClass.__init__
2023-07-20 16:42:49.734  1922-1995  python                  <pre-initialized>                    I  AttributeError: 'Class' object has no attribute '_JavaClass__cls_storage'
--------- beginning of crash
```

I don't know if that's related to the version issue. I'll see if I can reproduce.

**Comment by dbnicholson** [comment] 2023-07-20 17:54
Got the same error even after fixing the version issue. I suspect this is caused by a recent-ish pyjnius update, but we'll see.

**Comment by dbnicholson** [comment] 2023-07-20 18:06
This is being caused by `autoclass("android.os.Build$VERSION")` but I don't know why yet. I also don't think this is a pyjnius update since it's pinned to 1.4.2 in python-for-android.

**Comment by dbnicholson** [comment] 2023-07-20 19:28
Hmm, even `autoclass("java.util.Arrays")` is failing. Somehow jnius is totally hosed.

**Comment by dbnicholson** [comment] 2023-07-20 20:24
It took me a while to connect the dots after seeing an announcement for [Cython 3.0](https://lwn.net/Articles/938536/), but the problem is definitely in the C shared library portion of pyjnius. Downgrading it to the old 0.29 series got it working for me again.

**Closed as completed** 2023-07-20 21:00 UTC
Labels: bug

**Comment by dbnicholson** [comment] 2023-07-21 02:14
@vanessa-chang I [uploaded](https://ci.endlessos.org/view/Apps/job/kolibri-installer-android-upload/85/) version 374 to internal testing. Can you try it out?

**Comment by wjt** [comment] 2023-07-21 07:43
@vanessa-chang confirms

>  thanks for the good work! It works now!!!!
