### ISSUE TITLE
Review changes to Google Play Developer Program Policies

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-installer-android#162] opened 2023-07-17 05:52 UTC
We need to follow up on program policy changes. We received a message in the Google Play store July 12th: _We're introducing new policies and policy updates that need your attention. To learn about all the updates and when they will take effect, visit our [Policy Center](https://support.google.com/googleplay/android-developer/topic/12921780)._

**Comment by erikos** [comment] 2023-07-19 05:52
The one item that stood out was:

We're updating the list of example APIs or SDKs that are not approved for use in apps that solely target children as part of our [Families APIs and SDKs policy]

https://support.google.com/googleplay/android-developer/answer/13607332

**Comment by wjt** [comment] 2023-07-21 09:14
Duplicate of https://github.com/endlessm/endless-key-content-private/issues/78.

**Closed as completed by wjt** 2023-07-21 09:14 UTC
